apiVersion: apps/v1
kind: Deployment
metadata:
  ########Deployment 이름 작성 ##########
  name: practice3-deploy
  ##############################
  namespace: default
  labels:
    app: cns-cicd-sample
spec:
  ####### POD 수 작성 ############
  replicas: 1
  ##############################
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: cns-cicd-sample
  template:
    metadata:
      labels:
        app: cns-cicd-sample
    spec:
      containers:
        ########### POD 이름 작성 ############
        - name: practice3-pod
          ####################################
          ###########image 이름 ##############
          image: asia.gcr.io/_PROJECT_/practice3:0.1
         ####################################
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: practice3-service
  namespace: default
spec:
  selector:
    app: cns-cicd-sample
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
